name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.1.1
homepage: https://github.com/janstol/yeedart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  meta: ^1.1.8
  path: ^1.6.4

dev_dependencies:
  lint: ^1.1.0
  test: ^1.9.4
