name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.1.0
homepage: https://github.com/janstol/yeedart
author: Jan Štol <honzastol@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  meta: ^1.1.7

dev_dependencies:
  test: ^1.9.3
