name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.1.2
homepage: https://github.com/janstol/yeedart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  meta: ^1.1.8

dev_dependencies:
  lint: ^1.1.1
  path: ^1.6.4
  test: ^1.12.0
